name             'adpulse_db'
maintainer       'jugalkkt'
maintainer_email 'jugalkakkat@gmail.com'
license          'MIT'
description      'Configures the AdPulse PostgreSQL node: postgresql.conf, pg_hba.conf, roles, backups'
version          '0.1.0'
chef_version     '>= 18.0'
supports         'debian'
supports         'ubuntu'
