-- 002_seed: demo data (generated deterministically; 10 advertisers, 60 ads).
INSERT INTO advertisers (name) VALUES
    ('Northwind Sports'),
    ('Contoso Tech'),
    ('Fabrikam Fashion'),
    ('Tailspin Travel'),
    ('Woodgrove Finance'),
    ('Fourth Coffee'),
    ('Litware Gadgets'),
    ('Adventure Works'),
    ('Wide World Tours'),
    ('Proseware Foods')
ON CONFLICT (name) DO NOTHING;

INSERT INTO ads (advertiser_id, category, segment, title, image_url, click_url, bid_cpm)
SELECT a.id, v.category, v.segment, v.title, v.image_url, v.click_url, v.bid_cpm
FROM (VALUES
    ('Northwind Sports', 'sports', 'all', 'Northwind Sports: sports offer #1', 'https://cdn.adpulse.example/ads/1.png', 'https://adpulse.example/click/1', 10.3362),
    ('Adventure Works', 'sports', 'all', 'Adventure Works: sports offer #2', 'https://cdn.adpulse.example/ads/2.png', 'https://adpulse.example/click/2', 10.4646),
    ('Northwind Sports', 'sports', 'student', 'Northwind Sports: sports offer #3', 'https://cdn.adpulse.example/ads/3.png', 'https://adpulse.example/click/3', 4.8715),
    ('Northwind Sports', 'sports', 'young_professional', 'Northwind Sports: sports offer #4', 'https://cdn.adpulse.example/ads/4.png', 'https://adpulse.example/click/4', 5.7142),
    ('Adventure Works', 'sports', 'parent', 'Adventure Works: sports offer #5', 'https://cdn.adpulse.example/ads/5.png', 'https://adpulse.example/click/5', 10.0923),
    ('Northwind Sports', 'sports', 'retiree', 'Northwind Sports: sports offer #6', 'https://cdn.adpulse.example/ads/6.png', 'https://adpulse.example/click/6', 2.3705),
    ('Northwind Sports', 'sports', 'student', 'Northwind Sports: sports offer #7', 'https://cdn.adpulse.example/ads/7.png', 'https://adpulse.example/click/7', 4.5856),
    ('Northwind Sports', 'sports', 'young_professional', 'Northwind Sports: sports offer #8', 'https://cdn.adpulse.example/ads/8.png', 'https://adpulse.example/click/8', 8.2070),
    ('Northwind Sports', 'sports', 'parent', 'Northwind Sports: sports offer #9', 'https://cdn.adpulse.example/ads/9.png', 'https://adpulse.example/click/9', 8.5709),
    ('Northwind Sports', 'sports', 'retiree', 'Northwind Sports: sports offer #10', 'https://cdn.adpulse.example/ads/10.png', 'https://adpulse.example/click/10', 8.3608),
    ('Contoso Tech', 'tech', 'all', 'Contoso Tech: tech offer #11', 'https://cdn.adpulse.example/ads/11.png', 'https://adpulse.example/click/11', 1.3211),
    ('Litware Gadgets', 'tech', 'all', 'Litware Gadgets: tech offer #12', 'https://cdn.adpulse.example/ads/12.png', 'https://adpulse.example/click/12', 7.8023),
    ('Litware Gadgets', 'tech', 'student', 'Litware Gadgets: tech offer #13', 'https://cdn.adpulse.example/ads/13.png', 'https://adpulse.example/click/13', 6.6426),
    ('Contoso Tech', 'tech', 'young_professional', 'Contoso Tech: tech offer #14', 'https://cdn.adpulse.example/ads/14.png', 'https://adpulse.example/click/14', 3.3153),
    ('Contoso Tech', 'tech', 'parent', 'Contoso Tech: tech offer #15', 'https://cdn.adpulse.example/ads/15.png', 'https://adpulse.example/click/15', 5.8160),
    ('Contoso Tech', 'tech', 'retiree', 'Contoso Tech: tech offer #16', 'https://cdn.adpulse.example/ads/16.png', 'https://adpulse.example/click/16', 3.6044),
    ('Contoso Tech', 'tech', 'student', 'Contoso Tech: tech offer #17', 'https://cdn.adpulse.example/ads/17.png', 'https://adpulse.example/click/17', 11.1420),
    ('Contoso Tech', 'tech', 'young_professional', 'Contoso Tech: tech offer #18', 'https://cdn.adpulse.example/ads/18.png', 'https://adpulse.example/click/18', 8.4139),
    ('Contoso Tech', 'tech', 'parent', 'Contoso Tech: tech offer #19', 'https://cdn.adpulse.example/ads/19.png', 'https://adpulse.example/click/19', 3.0256),
    ('Contoso Tech', 'tech', 'retiree', 'Contoso Tech: tech offer #20', 'https://cdn.adpulse.example/ads/20.png', 'https://adpulse.example/click/20', 4.2293),
    ('Fabrikam Fashion', 'fashion', 'all', 'Fabrikam Fashion: fashion offer #21', 'https://cdn.adpulse.example/ads/21.png', 'https://adpulse.example/click/21', 9.3356),
    ('Adventure Works', 'fashion', 'all', 'Adventure Works: fashion offer #22', 'https://cdn.adpulse.example/ads/22.png', 'https://adpulse.example/click/22', 1.1433),
    ('Adventure Works', 'fashion', 'student', 'Adventure Works: fashion offer #23', 'https://cdn.adpulse.example/ads/23.png', 'https://adpulse.example/click/23', 9.9507),
    ('Fabrikam Fashion', 'fashion', 'young_professional', 'Fabrikam Fashion: fashion offer #24', 'https://cdn.adpulse.example/ads/24.png', 'https://adpulse.example/click/24', 9.7580),
    ('Adventure Works', 'fashion', 'parent', 'Adventure Works: fashion offer #25', 'https://cdn.adpulse.example/ads/25.png', 'https://adpulse.example/click/25', 5.1134),
    ('Adventure Works', 'fashion', 'retiree', 'Adventure Works: fashion offer #26', 'https://cdn.adpulse.example/ads/26.png', 'https://adpulse.example/click/26', 1.2612),
    ('Fabrikam Fashion', 'fashion', 'student', 'Fabrikam Fashion: fashion offer #27', 'https://cdn.adpulse.example/ads/27.png', 'https://adpulse.example/click/27', 11.0011),
    ('Fabrikam Fashion', 'fashion', 'young_professional', 'Fabrikam Fashion: fashion offer #28', 'https://cdn.adpulse.example/ads/28.png', 'https://adpulse.example/click/28', 7.0226),
    ('Adventure Works', 'fashion', 'parent', 'Adventure Works: fashion offer #29', 'https://cdn.adpulse.example/ads/29.png', 'https://adpulse.example/click/29', 8.7560),
    ('Adventure Works', 'fashion', 'retiree', 'Adventure Works: fashion offer #30', 'https://cdn.adpulse.example/ads/30.png', 'https://adpulse.example/click/30', 2.9452),
    ('Tailspin Travel', 'travel', 'all', 'Tailspin Travel: travel offer #31', 'https://cdn.adpulse.example/ads/31.png', 'https://adpulse.example/click/31', 6.2412),
    ('Wide World Tours', 'travel', 'all', 'Wide World Tours: travel offer #32', 'https://cdn.adpulse.example/ads/32.png', 'https://adpulse.example/click/32', 10.6739),
    ('Wide World Tours', 'travel', 'student', 'Wide World Tours: travel offer #33', 'https://cdn.adpulse.example/ads/33.png', 'https://adpulse.example/click/33', 7.8928),
    ('Tailspin Travel', 'travel', 'young_professional', 'Tailspin Travel: travel offer #34', 'https://cdn.adpulse.example/ads/34.png', 'https://adpulse.example/click/34', 2.1430),
    ('Tailspin Travel', 'travel', 'parent', 'Tailspin Travel: travel offer #35', 'https://cdn.adpulse.example/ads/35.png', 'https://adpulse.example/click/35', 2.1057),
    ('Wide World Tours', 'travel', 'retiree', 'Wide World Tours: travel offer #36', 'https://cdn.adpulse.example/ads/36.png', 'https://adpulse.example/click/36', 9.0674),
    ('Tailspin Travel', 'travel', 'student', 'Tailspin Travel: travel offer #37', 'https://cdn.adpulse.example/ads/37.png', 'https://adpulse.example/click/37', 6.6982),
    ('Tailspin Travel', 'travel', 'young_professional', 'Tailspin Travel: travel offer #38', 'https://cdn.adpulse.example/ads/38.png', 'https://adpulse.example/click/38', 9.0907),
    ('Wide World Tours', 'travel', 'parent', 'Wide World Tours: travel offer #39', 'https://cdn.adpulse.example/ads/39.png', 'https://adpulse.example/click/39', 5.4270),
    ('Tailspin Travel', 'travel', 'retiree', 'Tailspin Travel: travel offer #40', 'https://cdn.adpulse.example/ads/40.png', 'https://adpulse.example/click/40', 7.2106),
    ('Woodgrove Finance', 'finance', 'all', 'Woodgrove Finance: finance offer #41', 'https://cdn.adpulse.example/ads/41.png', 'https://adpulse.example/click/41', 4.6630),
    ('Contoso Tech', 'finance', 'all', 'Contoso Tech: finance offer #42', 'https://cdn.adpulse.example/ads/42.png', 'https://adpulse.example/click/42', 11.9692),
    ('Contoso Tech', 'finance', 'student', 'Contoso Tech: finance offer #43', 'https://cdn.adpulse.example/ads/43.png', 'https://adpulse.example/click/43', 2.0908),
    ('Contoso Tech', 'finance', 'young_professional', 'Contoso Tech: finance offer #44', 'https://cdn.adpulse.example/ads/44.png', 'https://adpulse.example/click/44', 6.1754),
    ('Contoso Tech', 'finance', 'parent', 'Contoso Tech: finance offer #45', 'https://cdn.adpulse.example/ads/45.png', 'https://adpulse.example/click/45', 9.1915),
    ('Woodgrove Finance', 'finance', 'retiree', 'Woodgrove Finance: finance offer #46', 'https://cdn.adpulse.example/ads/46.png', 'https://adpulse.example/click/46', 10.4027),
    ('Contoso Tech', 'finance', 'student', 'Contoso Tech: finance offer #47', 'https://cdn.adpulse.example/ads/47.png', 'https://adpulse.example/click/47', 2.2577),
    ('Woodgrove Finance', 'finance', 'young_professional', 'Woodgrove Finance: finance offer #48', 'https://cdn.adpulse.example/ads/48.png', 'https://adpulse.example/click/48', 2.3398),
    ('Contoso Tech', 'finance', 'parent', 'Contoso Tech: finance offer #49', 'https://cdn.adpulse.example/ads/49.png', 'https://adpulse.example/click/49', 8.3255),
    ('Woodgrove Finance', 'finance', 'retiree', 'Woodgrove Finance: finance offer #50', 'https://cdn.adpulse.example/ads/50.png', 'https://adpulse.example/click/50', 7.3587),
    ('Fourth Coffee', 'food', 'all', 'Fourth Coffee: food offer #51', 'https://cdn.adpulse.example/ads/51.png', 'https://adpulse.example/click/51', 4.9248),
    ('Proseware Foods', 'food', 'all', 'Proseware Foods: food offer #52', 'https://cdn.adpulse.example/ads/52.png', 'https://adpulse.example/click/52', 7.3527),
    ('Proseware Foods', 'food', 'student', 'Proseware Foods: food offer #53', 'https://cdn.adpulse.example/ads/53.png', 'https://adpulse.example/click/53', 5.8826),
    ('Proseware Foods', 'food', 'young_professional', 'Proseware Foods: food offer #54', 'https://cdn.adpulse.example/ads/54.png', 'https://adpulse.example/click/54', 3.3913),
    ('Fourth Coffee', 'food', 'parent', 'Fourth Coffee: food offer #55', 'https://cdn.adpulse.example/ads/55.png', 'https://adpulse.example/click/55', 6.8621),
    ('Fourth Coffee', 'food', 'retiree', 'Fourth Coffee: food offer #56', 'https://cdn.adpulse.example/ads/56.png', 'https://adpulse.example/click/56', 11.3380),
    ('Fourth Coffee', 'food', 'student', 'Fourth Coffee: food offer #57', 'https://cdn.adpulse.example/ads/57.png', 'https://adpulse.example/click/57', 8.3233),
    ('Fourth Coffee', 'food', 'young_professional', 'Fourth Coffee: food offer #58', 'https://cdn.adpulse.example/ads/58.png', 'https://adpulse.example/click/58', 1.8173),
    ('Proseware Foods', 'food', 'parent', 'Proseware Foods: food offer #59', 'https://cdn.adpulse.example/ads/59.png', 'https://adpulse.example/click/59', 10.6751),
    ('Fourth Coffee', 'food', 'retiree', 'Fourth Coffee: food offer #60', 'https://cdn.adpulse.example/ads/60.png', 'https://adpulse.example/click/60', 9.1351)
) AS v (advertiser, category, segment, title, image_url, click_url, bid_cpm)
JOIN advertisers a ON a.name = v.advertiser;
